//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tetris.rc
//
#define IDI_TETRIS                      1
#define IDM_MENU                        100
#define IDM_FILEMENU                    101
#define IDR_ACCELERATOR1                104
#define IDR_ACCELERATOR2                105
#define IDD_OPTIONS                     200
#define IDD_OPTIONS_KEYMAP              200
#define IDD_HIGHSCORES                  201
#define IDD_ABOUT                       202
#define IDD_OPTIONS_GAME                203
#define IDA_ACCEL                       300
#define IDT_TOOLBAR                     400
#define IDC_NEWGAME                     1000
#define IDC_OPTIONS                     1001
#define IDC_HIGHSCORES                  1002
#define IDC_ABOUT                       1003
#define IDC_EXIT                        1004
#define IDC_GRP_LEVEL                   1010
#define IDC_LEVEL_EASY                  1011
#define IDC_LEVEL_MODERATE              1012
#define IDC_LEVEL_HARD                  1013
#define IDC_GRP_OPTIONS                 1014
#define IDC_SOUND                       1015
#define IDC_DOUBLE_TAP                  1016
#define IDC_HARDDROP                    1016
#define IDC_PAUSEKEY                    1017
#define IDC_GRP_CONTROL                 1018
#define IDC_GRP_HALLOFFAME              1020
#define IDC_SCORELIST                   1021
#define IDC_SCORE_TAB                   1022
#define IDC_SCORE                       1023
#define IDC_CLEAR_SCORES                1025
#define IDC_SEND                        1026
#define IDC_RECEIVE                     1027
#define IDC_MOVEDOWN                    1030
#define IDC_ROTATELEFT                  1031
#define IDC_ROTATERIGHT                 1032
#define IDC_MOVELEFT                    1033
#define IDC_MOVERIGHT                   1034
#define IDC_PAUSE                       1040
#define ID_BUTTON1042                   1042
#define ID_BUTTON1044                   1044
#define IDC_REPEAT                      1044
#define IDC_GRP_KEYMAPPING              1047
#define IDC_TEST                        1051
#define IDC_COMBO2                      1052
#define IDC_COMBO3                      1053
#define IDC_COMBO4                      1054
#define IDC_REPEAT_RATE                 1054
#define IDC_COMBO5                      1055
#define IDC_GRP_KEYREPEAT               1055
#define IDC_COMBO6                      1056
#define IDC_COMBO7                      1057
#define IDB_BUBBLES                     2000
#define IDB_TOOLBAR                     2010
#define IDB_ABOUT                       2020
#define IDR_WAVE_DESTROY                3000
#define IDR_WAVE_DROP                   3001
#define IDS_TETRIS_TITLE                4000
#define IDS_CAP_FILE                    4001
#define IDS_FILE                        4002
#define IDS_SCORE                       4010
#define IDS_CLEAR_SCORES_BODY           4012
#define IDS_CLEAR_SCORES_HDR            4013
#define IDS_ERROR_IRDA_NO_SOCKET        4100
#define IDS_ERROR_IRDA_CANNOT_ENUMDEVS  4101
#define IDS_ERROR_IRDA_CANNOT_BIND      4102
#define IDS_ERROR_IRDA_CANNOT_LISTEN    4103
#define IDS_ERROR_IRDA_CANNOT_ACCEPT    4104
#define IDS_ERROR_IRDA_CANNOT_CONNECT   4105
#define IDS_ERROR_IRDA_CANNOT_SEND      4106
#define IDS_ERROR_IRDA_CANNOT_RECEIVE   4107
#define IDS_ERROR_NO_DEVICES_FOUND      4110
#define IDS_ERROR_INCOMPATIBLE_VERSIONS 4111
#define IDS_ERROR_INCOMPATIBLE_LEVELS   4112
#define IDS_ERROR_HIGHSCORE_RECEIVE     4113
#define IDS_ERROR_HIGHSCORE_SEND        4114
#define IDS_HIGHSCORE_SEND              4115
#define IDS_HIGHSCORE_RECEIVE           4116
#define IDS_HIGHSCORE_SENDTOHOST        4117
#define IDS_HIGHSCORE_SCORESMERGED      4118
#define IDS_HIGHSCORE_RECEIVEFROMHOST   4119
#define IDS_KEY_NONE                    4120
#define IDS_KEY_LEFT                    4121
#define IDS_KEY_RIGHT                   4122
#define IDS_KEY_UP                      4123
#define IDS_KEY_DOWN                    4124
#define IDS_KEY_ACTION                  4125
#define IDS_KEY_EXIT                    4126
#define IDS_KEY_PROG1                   4127
#define IDS_KEY_PROG2                   4128
#define IDS_KEY_PROG3                   4129
#define IDS_KEY_PROG4                   4130
#define IDS_KEY_PROG5                   4131
#define IDB_TETRIS                      5001
#define IDB_BACKGROUND                  5003
#define IDR_HITBOTTOM                   5004
#define IDR_WAVE_HITBOTTOM              5004
#define IDR_MOVEDOWN                    5005
#define IDR_WAVE_MOVEDOWN               5005
#define IDR_ROTATE                      5006
#define IDR_WAVE_ROTATE                 5006
#define IDC_MOVE_LEFT                   10000
#define IDC_MOVE_RIGHT                  10001
#define IDC_ROTATE_LEFT                 10002
#define IDC_ROTATE_RIGHT                10003
#define IDC_SOFT_DROP                   10004
#define IDC_HARD_DROP                   10005
#define IDC_PAUSE_RESUME                10006
#define IDM_MAIN_COMMAND1               40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
